[package]
name = "proc-macros"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.6.0"
deluxe = { version = "0.5.0", git = "https://code.lthoerner.com/deluxe" }
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = "2.0.76"

[lib]
proc-macro = true
