[[columns]]
view_key = "sku"
data_type = "integer"
display = { name = "SKU", trimmable = false }
formatting = { prefix = "#", pad_length = 10 }

[[columns]]
view_key = "display_name"
data_type = "string"
display = { name = "Name", trimmable = false }

[[columns]]
view_key = "count"
data_type = "integer"
display = { name = "Count", trimmable = false }

[[columns]]
view_key = "cost"
data_type = "decimal"
display = { name = "Cost", trimmable = false }
formatting = { prefix = "$" }

[[columns]]
view_key = "price"
data_type = "decimal"
display = { name = "Price", trimmable = false }
formatting = { prefix = "$" }
