[[tables]]
name = "inventory"
primary_column = { name = "sku", data_type = "integer" }
required_columns = [
    { name = "display_name", data_type = "string" },
    { name = "count", data_type = "integer" },
    { name = "cost", data_type = "decimal" },
    { name = "price", data_type = "decimal" },
]
optional_columns = []

[[tables]]
name = "customers"
primary_column = { name = "id", data_type = "integer" }
required_columns = [
    { name = "name", data_type = "string" },
    { name = "email", data_type = "string" },
    { name = "phone", data_type = "string" },
]
optional_columns = [{ name = "address", data_type = "string" }]

[[views]]
name = "inventory_view"
table = "inventory"
columns = [
    { name = "sku", display_name = "SKU", trimmable = false, formatting = { prefix = "#", pad_length = 10 } },
    { name = "display_name", display_name = "Name", trimmable = true },
    { name = "count", display_name = "Count", trimmable = false },
    { name = "cost", display_name = "Cost", trimmable = false, formatting = { prefix = "$" } },
    { name = "price", display_name = "Price", trimmable = false, formatting = { prefix = "$" } },
]

[[views]]
name = "customers_view"
table = "customers"
columns = [
    { name = "id", display_name = "ID", trimmable = false, formatting = { prefix = "#", pad_length = 10 } },
    { name = "name", display_name = "Name", trimmable = false },
    { name = "email", display_name = "Email", trimmable = true },
    { name = "phone", display_name = "Phone", trimmable = true },
    { name = "address", display_name = "Address", trimmable = true },
]
