[[tables]]
name = "inventory"
columns = [
    { name = "sku", display_name = "SKU", data_type = "integer", formatting = { prefix = "#", pad_length = 8 } },
    { name = "display_name", display_name = "Name", data_type = "string", required = true },
    { name = "count", display_name = "Count", data_type = "integer", required = true },
    { name = "cost", display_name = "Cost", data_type = "decimal", required = true, formatting = { prefix = "$" } },
    { name = "price", display_name = "Price", data_type = "decimal", required = true, formatting = { prefix = "$" } },
]

[[tables]]
name = "customers"
columns = [
    { name = "id", display_name = "ID", data_type = "integer" },
    { name = "name", display_name = "Name", data_type = "string", required = true },
    { name = "email", display_name = "Email", data_type = "string", required = true },
    { name = "phone", display_name = "Phone", data_type = "string", required = true },
    { name = "address", display_name = "Address", data_type = "string", required = false },
]
