[[tables]]
name = "inventory"
columns = [
    { name = "sku", display_name = "SKU", data_type = "integer" },
    { name = "display_name", display_name = "Name", data_type = "string" },
    { name = "count", display_name = "Count", data_type = "integer" },
    { name = "cost", display_name = "Cost", data_type = "decimal" },
    { name = "price", display_name = "Price", data_type = "decimal" },
]
